server:
  ssl:
    key-store: classpath:certificate/localhost/localhost.p12
    key-store-password: localhost
    key-alias: 1
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://brick2.xtu:19906/realestate
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: none
    show-sql: true

  thymeleaf:
    prefix: file:///C:/Projects/inventorer/src/main/resources/templates/

  web:
    resources:
      static-locations: file:src/main/resources/static #used for dev to not cache scripts etc.